AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for HelloWorld

Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Resources:
  
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - dynamodb:DescribeStream
                  - dynamodb:GetRecords
                  - dynamodb:GetShardIterator
                  - dynamodb:ListStreams
                Resource: !GetAtt MediaTable.StreamArn
                
  MediaTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "DynamoDBStreamTable"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: True
      SSESpecification:
        SSEEnabled: true
      AttributeDefinitions:
        - AttributeName: "partitionId"
          AttributeType: S
        - AttributeName: "id"
          AttributeType: S
      KeySchema:
        - AttributeName: "partitionId"
          KeyType: HASH
        - AttributeName: "id"
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  
  DynamodbFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/DynamodbFunction/
      Handler: DynamodbFunction::DynamodbFunction.Function::FunctionHandler
      Runtime: dotnet6
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      MemorySize: 256
      Environment:
        Variables:
          PARAM1: VALUE
            
  EventMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 1
      Enabled: True
      EventSourceArn: !GetAtt MediaTable.StreamArn
      FunctionName: !GetAtt DynamodbFunction.Arn
      StartingPosition: LATEST

Outputs:
  DynamodbFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt DynamodbFunction.Arn
  DynamoDBTable:
    Description: "Dynamo table ARN"
    Value: !GetAtt MediaTable.StreamArn